clc
clear all
close all

% ----------------------------------- EXERCISE 6 ------------------------------------
% --- Part 1: sampling from Poisson distributions: Metropolis-Hastings Algorithm  ---

% N_obs=[1,2,3,4]*10^5; s=0.95*N_obs; % Sample size and burn-in: discard 95% first values
% figure % (one subplot per N_obs value)
% 
% for k=1:1:length(N_obs)
% 
% X = zeros(1,N_obs(k));
% A=8; m=10; n=1; i=0;       % Parameters and initial state
% while n<=N_obs(k)
%    delta=randi(m+1)-1;     % Random walk perturbation: delta from 0 to m
%    j = mod(i+delta, m+1);  % symmetric: if i+delta > m+1, start from 0
%    if rand<=min(1, (A^j/factorial(j))/(A^i/factorial(i)))
%        i=j; % If proposal accepted
%    end 
%    X(n)=i; n=n+1; 
% end          
% 
% % Chi^2 test
% x = 0:(m+1);
% P=poisspdf(0:m,A)/sum(poisspdf(0:m,A));
% O = histcounts(X((s(k)+1):end),x);
% E = length(X((s(k)+1):end))*P;
% T(k) = sum((O-E).^2 ./ E);  % Test statistic
% if T < chi2inv(0.975,m) % Critical value for significance level alpha=0.025
%     disp(['Chi-square test truncated Poisson distribution: null hypothesis not rejected for ' num2str(N_obs(k))])
% end
% 
% subplot(1,4,k)
% histogram(X((s(k)+1):end),0:m+1,'Normalization','count') % Empirical truncated poisson
% hold on
% stairs(0:m,(N_obs(k)-s(k))*P);                           % Theoretical truncated poisson
% title(['N_{obs} = ' num2str(N_obs(k))])
% xlabel('X')
% ylabel('Counts')
% 
% end

% ----------------------------------- EXERCISE 6 ---------------------------------------
% --- Part 2: sampling from 2D Poisson distributions: MH Algorithm and Gibbs sampler ---

N_obs=4*10^5; s=0.95*N_obs; % Sample size and burn-in: discard 95% first values

% -------------- Empirical truncated poisson MH 2D
    X_MH_2D = zeros(2,N_obs);
    A=4; m=10; n=1; i_1=0; j_1=0; m_1=0; % Parameters and initial state
    while n<=N_obs
        delta=randi((m+1)^2)-1;         % Random walk perturbation: generate a global index for the grid of possible values
        m_2 = mod(m_1+delta, (m+1)^2);  % symmetric: if i+delta > m+1, start from 0

        i_2 = mod(m_2,m+1); j_2= floor(m_2/(m+1)); % Find the coordinates i_2,j_2 corresponding to m_2 in the grid of possible values
        if i_2 + j_2 <= m 
            if rand<=min(1, (A^j_2/factorial(j_2))*(A^i_2/factorial(i_2))/((A^j_1/factorial(j_1))*(A^i_1/factorial(i_1))))
                i_1=i_2; j_1=j_2; m_1=m_2; % If proposal accepted
            end 
        end
         X_MH_2D(1,n)=i_1; X_MH_2D(2,n)=j_1; n=n+1; 
    end          
   
    % ---------- Empirical truncated poisson MH Columnwise
    X_MH_2D_comp = zeros(2,N_obs);
    A=4; m=10; n=1; i_1=0; j_1=0; % Parameters and initial state
    while n<=N_obs
        
        delta=randi(m+1)-1;     % Random walk perturbation: delta from 0 to m
        i_2 = mod(i_1+delta, m+1);  % symmetric: if i+delta > m+1, start from 0
        if i_2+j_1<=m
            if rand<=min(1, (A^i_2/factorial(i_2))/(A^i_1/factorial(i_1)))
                i_1=i_2; % If proposal accepted
            end 
        end
        
        delta=randi(m+1)-1;     % Random walk perturbation: delta from 0 to m
        j_2 = mod(j_1+delta, m+1);  % symmetric: if i+delta > m+1, start from 0
        if  i_1+j_2<=m
            if rand<=min(1, (A^j_2/factorial(j_2))/(A^j_1/factorial(j_1)))
                j_1=j_2;  % If proposal accepted
            end 
        end
        X_MH_2D_comp(1,n)=i_1; X_MH_2D_comp(2,n)=j_1; n=n+1; 
    end   

    % -----Empirical truncated poisson Gibbs sampling 2D using direct method

    X_Gibbs_2D = zeros(2,N_obs);
    A_1 = 4; A_2 = 4; m = 10; n = 1; i_1 = 0; j_1 = 0;
    while n <= N_obs
        % ----- New sample j given i_1 -----
        i_states = 0:(m-j_1); % Based on the previous values of the other variables, the cond distrib is:
        F_i = cumsum((A_1.^i_states)./factorial(i_states)/sum((A_1.^i_states)./factorial(i_states)));
        i_1 = i_states(find(rand <= F_i,1)); % New sample is generated by finding the corresponding i

        % ----- New sample j given i_1 -----
        j_states = 0:(m-i_1); % Based on the previous values of the other variables, the cond distrib is:
        F_j = cumsum((A_2.^j_states)./factorial(j_states)/sum((A_2.^j_states)./factorial(j_states)));
        j_1 = j_states(find(rand <= F_j,1)); % New sample is generated by finding the corresponding j

        X_Gibbs_2D(1,n) = i_1; X_Gibbs_2D(2,n) = j_1; n = n+1;

    end

% ---------- Chi^2 tests

P=zeros(m+1,m+1);
for i=0:m
for j=0:m 
if i+j<=m
P(i+1,j+1)=(A^i/factorial(i))*(A^j/factorial(j));
end
end      % Theoretical treuncated Poisson distrib
end
P=P/sum(P(:)); % Theoretical treuncated Poisson distrib (with 0 in not valid values)
filter=P>0; % Filter and use only values for which E is not 0 (distrib is defined)
T_crit=chi2inv(0.975,sum(filter(:))-1); % Crit.val. for Chi(v)^2, where v=possible states-1-0

O=histcounts2(X_MH_2D(1,(s+1):end),X_MH_2D(2,(s+1):end),0:m+1,0:m+1); O=O';
E=length(X_MH_2D(1,(s+1):end))*P;
T_MH_2D=sum((O(filter)-E(filter)).^2./E(filter));
disp(['T MH 2D = ' num2str(T_MH_2D)])

O=histcounts2(X_MH_2D_comp(1,(s+1):end),X_MH_2D_comp(2,(s+1):end),0:m+1,0:m+1); O=O';
E=length(X_MH_2D_comp(1,(s+1):end))*P;
T_MH_2D_comp=sum((O(filter)-E(filter)).^2./E(filter));
disp(['T MH Columnwise = ' num2str(T_MH_2D_comp)])

O=histcounts2(X_Gibbs_2D(1,(s+1):end),X_Gibbs_2D(2,(s+1):end),0:m+1,0:m+1); O=O';
E=length(X_Gibbs_2D(1,(s+1):end))*P;
T_Gibbs_2D=sum((O(filter)-E(filter)).^2./E(filter));
disp(['T Gibbs = ' num2str(T_Gibbs_2D)])

% ---------- Histograms in three dimensions

figure

subplot(1,3,1)
histogram2(X_MH_2D(1,(s+1):end),X_MH_2D(2,(s+1):end), 0:m+1,0:m+1,'DisplayStyle','bar3')
hold on
h=bar3(0:m,0:m,(N_obs-s)*P);      % This plots
for k=1:length(h)                 % theoretical
    h(k).FaceAlpha=0.3;           % distribution
end                               % transparent
title('MH 2D')
xlabel('i')
ylabel('j')
zlabel('Counts')

subplot(1,3,2)
histogram2(X_MH_2D_comp(1,(s+1):end),X_MH_2D_comp(2,(s+1):end), ...
    0:m+1,0:m+1,'DisplayStyle','bar3')
hold on
h=bar3(0:m,0:m,(N_obs-s)*P);  % This plots
for k=1:length(h)             % theoretical
    h(k).FaceAlpha=0.3;       % distribution
end                           % transparent
title('MH Columnwise')
xlabel('i')
ylabel('j')
zlabel('Counts')

subplot(1,3,3)
histogram2(X_Gibbs_2D(1,(s+1):end),X_Gibbs_2D(2,(s+1):end), ...
    0:m+1,0:m+1,'DisplayStyle','bar3')
hold on
h=bar3(0:m,0:m,(N_obs-s)*P); % This plots
for k=1:length(h)            % theoretical
    h(k).FaceAlpha=0.3;      % distribution
end                          % transparent
title('Gibbs')
xlabel('i')
ylabel('j')
zlabel('Counts')
